### ISSUE TITLE
Upon clicking 'play' video player should load smaller standard dimension video player (not full screen)

### ISSUE THREAD

**Issue by mollieru** [kpenning/peoplepower#27]
Presently the embedded video is stretching to the full screen. Instead, we should have a static image for the background (which I am working on) which, upon click, loads a smaller standard dimension livestream video player.  This is demonstrated on the Bernie streaming page below:

![kyxuxxwm1x](https://cloud.githubusercontent.com/assets/3680494/23722303/d5c0e94e-0412-11e7-8941-339a652ab7bb.gif)

**Comment by liyanchang** [comment]
So the youtube video player will self adjust and the video won't get stretched. I can see doing this to keep the video controls closer

**Comment by liyanchang** [comment]
Done. See #29
