### ISSUE TITLE
Add image assets for background and 'play' button

### ISSUE THREAD

**Issue by mollieru** [kpenning/peoplepower#28]
Load in background image and 'play' button. Image assets below.

Hover state specs:
- hover state: 70% opacity
- max-width: 150px

![peoplepower_livestreamscreen_hero_1](https://cloud.githubusercontent.com/assets/3680494/23723555/a68f890a-0417-11e7-8d7b-1b52c240b4d9.png)
![playbutton](https://cloud.githubusercontent.com/assets/3680494/23723557/a6cd64aa-0417-11e7-88cd-8cdbb58dcd1a.png)

**Comment by liyanchang** [comment]
Done. Thanks!

**Comment by liyanchang** [comment]
See #29
